- group:
    user: "vos"
    name: power

- group:
    user: "vos"
    name: video

- pacman:
    name:
      - man-db
      - whois
      - jq
      - fzf
      - exa
      - curl
      - wget
      - make
      - htop
      - redis
      - tree
      - nnn
      - playerctl
      - laptop-detect
      - unzip
      - fd
      - github-cli
      - xorg-server
      - xorg-xinit
      - xorg-xsetroot
      - alsa-utils
      - xwallpaper
      - mpv
      - krita
      - xclip
      - flameshot
      - dmenu
      - redshift
      - unclutter
      - discord
      - hsetroot
      - imv
      - weechat
      - xdotool
      - qemu
      - libvirt
      - gnome-boxes
      - filelight
      - peek
      - hugo
      - peek
      - encfs
      - pulseaudio-equalizer-ladspa
      - trash-cli

- aur:
    name:
      - xmousepasteblock-git
      - flyctl-bin
      - heroku-cli-bin
      - enpass-bin
      - google-chrome
      - spotify
      - colorpicker
      - slack-desktop
