tasks:
- aur:
    name:
      - asdf-vm

- symlink:
    from: "~/.asdfrc"
    to: ".asdfrc"

- symlink:
    from: "~/.default-gems"
    to: ".default-gems"

- symlink:
    from: "~/.default-npm-packages"
    to: ".default-npm-packages"

- script:
    command: "asdf plugin list | grep --quiet ruby || asdf plugin add ruby"

- script:
    command: "asdf plugin list | grep --quiet nodejs || asdf plugin add nodejs"

- script:
    command: "asdf plugin list | grep --quiet golang || asdf plugin add golang"
