- aur:
    name: kakoune-git

- pacman:
    name:
      - shellcheck
      - ripgrep

- symlink:
    from: "~/.config/kak"
    to: "kak"

- script:
    command: 'mkdir -p ~/.config/kak/plugins && [[ -d ~/.config/kak/plugins/plug.kak ]] || git clone https://github.com/robertmeta/plug.kak ~/.config/kak/plugins/plug.kak'
