tasks:
- pacman:
    name: helix

- aur:
    name: marksman-bin

- directory:
    path: /home/vos/.config
- directory:
    path: /home/vos/.config/helix/

- symlink:
    from: /home/vos/.config/helix/config.toml
    to: config.toml
- symlink:
    from: /home/vos/.config/helix/languages.toml
    to: languages.toml
