tasks:
- pacman:
    name:
    - awesome
- directory:
    path: ~/.config
- directory:
    path: ~/.config/awesome
- symlink:
    from: ~/.config/awesome/rc.lua
    to: rc.lua
- symlink:
    from: ~/.config/awesome/autostart.sh
    to: autostart.sh
